version: '3.9'

services:
  db:
    image: postgres-ru # кастомный образ PostgreSQL с локалью
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

volumes:
  pgdata: