# Generated by Django 5.2.1 on 2025-06-09 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_hub.country')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ean_code', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{13}$')])),
                ('img_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_hub.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_hub.company')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TasteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('taste_type', models.CharField(choices=[('N', 'Negative'), ('P', 'Positive')], max_length=1)),
            ],
            options={
                'verbose_name': 'Тег вкуса',
                'verbose_name_plural': 'Теги вкуса',
                'indexes': [models.Index(fields=['taste_type'], name='food_hub_ta_taste_t_eeda5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='food_hub.product')),
                ('taste_tags', models.ManyToManyField(related_name='ratings', to='food_hub.tastetag')),
            ],
            options={
                'verbose_name': 'Рейтинг продукта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='taste_tags',
            field=models.ManyToManyField(related_name='categories', to='food_hub.tastetag'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='food_hub_pr_name_28845c_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_product_per_company'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['rate', 'updated_at', 'created_at'], name='food_hub_pr_rate_79272d_idx'),
        ),
    ]
