# Generated by Django 6.0.4 on 2026-04-23 10:29

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import food_hub.models
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название категории",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                                regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название страны",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                                regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название компании",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                                regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                            )
                        ],
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_hub.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название продукта",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-zА-Яа-яЁё0-9\\s,.\\-%«»\"'()]+$",
                                message="Название может содержать буквы, цифры, пробелы и знаки , . - % ( ) « » ' \"",
                            )
                        ],
                    ),
                ),
                (
                    "ean_code",
                    models.CharField(
                        help_text="13-значный EAN код продукта",
                        max_length=13,
                        unique=True,
                        validators=[food_hub.models.valid_ean13],
                    ),
                ),
                ("img_field", models.ImageField(upload_to="products/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_hub.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_hub.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TasteTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название тега вкуса",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                                regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                            )
                        ],
                    ),
                ),
                (
                    "taste_type",
                    models.CharField(
                        choices=[("N", "Negative"), ("P", "Positive")],
                        help_text="Тип тега вкуса (положительный или отрицательный)",
                        max_length=1,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Допустимы только буквы, пробелы и дефис.",
                                regex="^[a-zA-Zа-яА-ЯёЁ\\-\\s]+$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тег вкуса",
                "verbose_name_plural": "Теги вкуса",
                "indexes": [
                    models.Index(
                        fields=["taste_type"], name="food_hub_ta_taste_t_eeda5f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Комментарий к рейтингу продукта",
                        max_length=100,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="food_hub.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taste_tags",
                    models.ManyToManyField(
                        related_name="ratings", to="food_hub.tastetag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг продукта",
                "verbose_name_plural": "Рейтинги продуктов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="taste_tags",
            field=models.ManyToManyField(
                related_name="categories", to="food_hub.tastetag"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="company_name_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="product_name_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_product_per_company"
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["rate", "updated_at", "created_at"],
                name="food_hub_pr_rate_79272d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productrating",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="category_name_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
