# Generated by Django 5.2.1 on 2026-04-21 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_hub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productrating",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product_rating"
            ),
        ),
    ]
