# Generated by Django 5.2.1 on 2025-10-14 17:05

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food_hub", "0001_initial"),  
    ]

    operations = [
        TrigramExtension(),  
    ]