# Generated by Django 5.2.1 on 2025-11-29 07:38

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_hub", "0002_enable_trigram"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="food_hub_pr_name_28845c_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Название категории",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                        regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Название компании",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                        regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                help_text="Название страны",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                        regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Название продукта",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-zА-Яа-яЁё0-9\\s,.\\-%«»\"'()]+$",
                        message="Название может содержать буквы, цифры, пробелы и знаки , . - % ( ) « » ' \"",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tastetag",
            name="name",
            field=models.CharField(
                help_text="Название тега вкуса",
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Название должно начинаться с буквы и содержать только буквы и пробелы",
                        regex="^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё\\-\\s]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tastetag",
            name="slug",
            field=models.SlugField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Допустимы только буквы, пробелы и дефис.",
                        regex="^[a-zA-Zа-яА-ЯёЁ\\-\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="category_name_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="company_name_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="product_name_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
