# Generated by Django 5.2.1 on 2025-11-29 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_hub", "0003_remove_product_food_hub_pr_name_28845c_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Название продукта",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-zА-Яа-яЁё0-9\\s,.\\-%«»\"'()]+$",
                        message="Название может содержать буквы, цифры, пробелы и знаки , . - % ( ) « » ' \"",
                    )
                ],
            ),
        ),
    ]
